# Generated by Django 4.0.2 on 2022-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_url_original_url_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='counts',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
