# Generated by Django 4.0.2 on 2022-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220617_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerdata',
            name='ip_address',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
