# Generated by Django 4.0.2 on 2022-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=512, unique=True)),
                ('short_url', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
